# Generated by Django 2.2.2 on 2021-02-01 07:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import equipments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Equipment_name', models.CharField(max_length=50, unique=True)),
                ('detail', models.TextField(max_length=5000)),
                ('image', models.ImageField(null=True, upload_to=equipments.models.upload_location)),
                ('price', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('availablity', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
